export type JokerRarity = 'common' | 'uncommon' | 'rare' | 'legendary';

export interface JokerDefinition {
  id: string;
  name: string;
  rarity: JokerRarity;
  cost: number;
  effect: string;
  glyph: string;
  accent: string;
  artIndex: number;
}

const COLORS: Record<JokerRarity, string> = {
  common: '#ef5f6f',
  uncommon: '#48b8df',
  rare: '#ddab42',
  legendary: '#8f62d8'
};

const joker = (
  id: string,
  name: string,
  rarity: JokerRarity,
  cost: number,
  effect: string,
  glyph = name.slice(0, 1)
): Omit<JokerDefinition, 'artIndex'> => ({ id, name, rarity, cost, effect, glyph, accent: COLORS[rarity] });

// All 150 Jokers from Balatro's collection. Visuals are original to this project.
const JOKER_DEFINITIONS: Array<Omit<JokerDefinition, 'artIndex'>> = [
  joker('8-ball', '8 Ball', 'common', 5, 'Scored 8s can generate $2', '8'),
  joker('abstract', 'Abstract Joker', 'common', 4, '+3 Mult for every owned Joker', 'A'),
  joker('banner', 'Banner', 'common', 5, '+30 Chips per remaining discard', '⚑'),
  joker('blue-joker', 'Blue Joker', 'common', 5, '+2 Chips per card left in the deck', 'B'),
  joker('business-card', 'Business Card', 'common', 4, 'Scored face cards can earn $2', '$'),
  joker('cavendish', 'Cavendish', 'common', 4, 'X3 Mult', '🍌'),
  joker('chaos', 'Chaos the Clown', 'common', 4, 'First shop reroll is free', 'C'),
  joker('clever', 'Clever Joker', 'common', 4, '+80 Chips on Two Pair', '2'),
  joker('crafty', 'Crafty Joker', 'common', 4, '+80 Chips on a Flush', '♣'),
  joker('crazy', 'Crazy Joker', 'common', 4, '+12 Mult on a Straight', '5'),
  joker('credit-card', 'Credit Card', 'common', 1, 'Purchases may take you down to -$20', '¢'),
  joker('delayed-gratification', 'Delayed Gratification', 'common', 4, 'Earn $2 per unused discard after a blind', '⌛'),
  joker('devious', 'Devious Joker', 'common', 4, '+100 Chips on a Straight', '5'),
  joker('droll', 'Droll Joker', 'common', 4, '+10 Mult on a Flush', '♠'),
  joker('drunkard', 'Drunkard', 'common', 4, '+1 discard each blind', 'D'),
  joker('egg', 'Egg', 'common', 4, 'Sell value grows by $3 after each blind', '🥚'),
  joker('even-steven', 'Even Steven', 'common', 4, 'Even ranked scoring cards give +4 Mult', '4'),
  joker('faceless', 'Faceless Joker', 'common', 4, 'Discarding 3 face cards earns $5', '□'),
  joker('fortune-teller', 'Fortune Teller', 'common', 6, '+1 Mult for each hand played this run', '🔮'),
  joker('gluttonous', 'Gluttonous Joker', 'common', 5, 'Scored Clubs give +3 Mult', '♣'),
  joker('golden-joker', 'Golden Joker', 'common', 6, 'Earn $4 after every blind', '$'),
  joker('golden-ticket', 'Golden Ticket', 'common', 5, 'Scored face cards can earn $4', '🎟'),
  joker('greedy', 'Greedy Joker', 'common', 5, 'Scored Diamonds give +3 Mult', '♦'),
  joker('green-joker', 'Green Joker', 'common', 4, 'Gains +1 Mult per hand, loses 1 per discard', 'G'),
  joker('gros-michel', 'Gros Michel', 'common', 5, '+15 Mult', '🍌'),
  joker('half-joker', 'Half Joker', 'common', 5, '+20 Mult when playing 3 cards or fewer', '½'),
  joker('hallucination', 'Hallucination', 'common', 4, 'Buying a Joker can refund $2', 'H'),
  joker('hanging-chad', 'Hanging Chad', 'common', 4, 'First scoring card triggers 2 extra times', '☷'),
  joker('ice-cream', 'Ice Cream', 'common', 5, '+100 Chips, loses 5 after each hand', '🍦'),
  joker('joker', 'Joker', 'common', 2, '+4 Mult', 'J'),
  joker('jolly', 'Jolly Joker', 'common', 3, '+8 Mult on a Pair', '2'),
  joker('juggler', 'Juggler', 'common', 4, '+1 hand size', '⚾'),
  joker('lusty', 'Lusty Joker', 'common', 5, 'Scored Hearts give +3 Mult', '♥'),
  joker('mad', 'Mad Joker', 'common', 4, '+10 Mult on Two Pair', '2'),
  joker('mail-in-rebate', 'Mail-In Rebate', 'common', 4, 'Discarded 5s earn $5', '✉'),
  joker('misprint', 'Misprint', 'common', 4, 'Adds a random 0-23 Mult', '?'),
  joker('mystic-summit', 'Mystic Summit', 'common', 5, '+15 Mult with no discards left', '▲'),
  joker('odd-todd', 'Odd Todd', 'common', 4, 'Odd ranked scoring cards give +31 Chips', '7'),
  joker('photograph', 'Photograph', 'common', 5, 'First scored face card gives X2 Mult', '▣'),
  joker('popcorn', 'Popcorn', 'common', 5, '+20 Mult, loses 4 after each blind', '🍿'),
  joker('raised-fist', 'Raised Fist', 'common', 5, 'Lowest held rank adds double its value to Mult', '✊'),
  joker('red-card', 'Red Card', 'common', 5, 'Skipping a blind permanently adds +3 Mult', 'R'),
  joker('reserved-parking', 'Reserved Parking', 'common', 6, 'Held face cards can earn $1', 'P'),
  joker('ride-the-bus', 'Ride the Bus', 'common', 6, 'Gains +1 Mult for hands without scoring faces', '🚌'),
  joker('riff-raff', 'Riff-raff', 'common', 6, 'Selecting a blind creates one free Common Joker', 'R'),
  joker('runner', 'Runner', 'common', 5, 'Straights permanently add +15 Chips', '🏃'),
  joker('scary-face', 'Scary Face', 'common', 4, 'Scored face cards give +30 Chips', '☹'),
  joker('scholar', 'Scholar', 'common', 4, 'Scored Aces give +20 Chips and +4 Mult', 'A'),
  joker('shoot-the-moon', 'Shoot the Moon', 'common', 5, 'Held Queens give +13 Mult each', 'Q'),
  joker('sly', 'Sly Joker', 'common', 3, '+50 Chips on a Pair', '2'),
  joker('smiley-face', 'Smiley Face', 'common', 4, 'Scored face cards give +5 Mult', '☺'),
  joker('splash', 'Splash', 'common', 3, 'Every played card scores', '💦'),
  joker('square', 'Square Joker', 'common', 4, 'Four-card hands permanently add +4 Chips', '□'),
  joker('supernova', 'Supernova', 'common', 5, 'Adds times this poker hand was played to Mult', '✦'),
  joker('superposition', 'Superposition', 'common', 4, 'Ace-high Straights earn $4', 'A'),
  joker('swashbuckler', 'Swashbuckler', 'common', 4, 'Adds other Jokers sell value to Mult', '⚔'),
  joker('to-do-list', 'To Do List', 'common', 4, 'Playing the marked hand earns $4', '✓'),
  joker('walkie-talkie', 'Walkie Talkie', 'common', 4, 'Scored 10s and 4s give +10 Chips and +4 Mult', '10'),
  joker('wily', 'Wily Joker', 'common', 4, '+100 Chips on Three of a Kind', '3'),
  joker('wrathful', 'Wrathful Joker', 'common', 5, 'Scored Spades give +3 Mult', '♠'),
  joker('zany', 'Zany Joker', 'common', 4, '+12 Mult on Three of a Kind', '3'),
  joker('acrobat', 'Acrobat', 'uncommon', 6, 'X3 Mult on the final hand', 'A'),
  joker('arrowhead', 'Arrowhead', 'uncommon', 7, 'Scored Spades give +50 Chips', '♠'),
  joker('astronomer', 'Astronomer', 'uncommon', 8, 'Shop rerolls cost $2 less', '★'),
  joker('blackboard', 'Blackboard', 'uncommon', 6, 'X3 Mult when all held cards are black suits', '▰'),
  joker('bloodstone', 'Bloodstone', 'uncommon', 7, 'Scored Hearts can give X1.5 Mult', '♥'),
  joker('bootstraps', 'Bootstraps', 'uncommon', 7, '+2 Mult for every $5 owned', '🥾'),
  joker('bull', 'Bull', 'uncommon', 6, '+2 Chips for each dollar owned', '♉'),
  joker('burglar', 'Burglar', 'uncommon', 6, '+3 hands and no discards each blind', 'B'),
  joker('card-sharp', 'Card Sharp', 'uncommon', 6, 'X3 Mult after repeating a hand type this blind', '♯'),
  joker('cartomancer', 'Cartomancer', 'uncommon', 6, 'Selecting a blind earns $3', 'C'),
  joker('castle', 'Castle', 'uncommon', 6, 'Discarded Spades permanently add +3 Chips', '♜'),
  joker('ceremonial-dagger', 'Ceremonial Dagger', 'uncommon', 6, 'Selling a Joker adds double its value to Mult', '†'),
  joker('certificate', 'Certificate', 'uncommon', 6, '+1 hand size at the start of each blind', '⌘'),
  joker('cloud-9', 'Cloud 9', 'uncommon', 7, 'Earn $1 per 9 in the deck after each blind', '9'),
  joker('constellation', 'Constellation', 'uncommon', 6, 'Gains X0.1 Mult whenever a hand is played', '✧'),
  joker('diet-cola', 'Diet Cola', 'uncommon', 6, 'Selling grants $8', '🥤'),
  joker('dusk', 'Dusk', 'uncommon', 5, 'All cards retrigger on the final hand', '☾'),
  joker('erosion', 'Erosion', 'uncommon', 6, '+4 Mult per card missing from a 52-card deck', 'E'),
  joker('fibonacci', 'Fibonacci', 'uncommon', 8, 'A, 2, 3, 5 and 8 give +8 Mult when scored', 'φ'),
  joker('flash-card', 'Flash Card', 'uncommon', 5, 'Every shop reroll permanently adds +2 Mult', '⚡'),
  joker('flower-pot', 'Flower Pot', 'uncommon', 6, 'X3 Mult when all four suits score', '✿'),
  joker('four-fingers', 'Four Fingers', 'uncommon', 7, 'Straights and Flushes can use four cards', '4'),
  joker('gift-card', 'Gift Card', 'uncommon', 6, 'All owned Jokers gain $1 sell value per blind', '🎁'),
  joker('glass-joker', 'Glass Joker', 'uncommon', 6, 'X1.5 Mult after every 4 hands played', '◇'),
  joker('hack', 'Hack', 'uncommon', 6, 'Scored 2-5 cards retrigger', '#'),
  joker('hiker', 'Hiker', 'uncommon', 5, 'Each scoring card permanently adds +5 Chips', '⛰'),
  joker('hologram', 'Hologram', 'uncommon', 7, 'Gains X0.25 Mult whenever hand size grows', 'H'),
  joker('joker-stencil', 'Joker Stencil', 'uncommon', 8, 'X1 Mult per empty Joker slot', '▧'),
  joker('loyalty-card', 'Loyalty Card', 'uncommon', 5, 'Every sixth hand gains X4 Mult', '6'),
  joker('luchador', 'Luchador', 'uncommon', 5, 'Boss Blinds require 25% fewer Chips', 'L'),
  joker('lucky-cat', 'Lucky Cat', 'uncommon', 6, 'Gains X0.25 Mult after lucky scoring hands', '🐈'),
  joker('madness', 'Madness', 'uncommon', 7, 'Gains X0.5 Mult when a non-Boss Blind starts', 'M'),
  joker('marble', 'Marble Joker', 'uncommon', 6, '+25 Chips whenever a blind is selected', '●'),
  joker('matador', 'Matador', 'uncommon', 7, 'Beating a Boss Blind earns $8 extra', 'M'),
  joker('merry-andy', 'Merry Andy', 'uncommon', 7, '+3 discards, -1 hand size', 'A'),
  joker('midas-mask', 'Midas Mask', 'uncommon', 7, 'Scored face cards earn $1', 'M'),
  joker('mime', 'Mime', 'uncommon', 5, 'Held-card effects trigger twice', 'M'),
  joker('mr-bones', 'Mr. Bones', 'uncommon', 5, 'Survive a failed blind above 25% once', '☠'),
  joker('onyx-agate', 'Onyx Agate', 'uncommon', 7, 'Scored Clubs give +7 Mult', '♣'),
  joker('oops-all-6s', 'Oops! All 6s', 'uncommon', 4, 'Doubles listed random probabilities', '6'),
  joker('pareidolia', 'Pareidolia', 'uncommon', 5, 'Every card counts as a face card', '☺'),
  joker('ramen', 'Ramen', 'uncommon', 6, 'Starts at X2 Mult and loses X0.01 per discarded card', '🍜'),
  joker('rocket', 'Rocket', 'uncommon', 6, 'Earn $1 after each Blind, gains $2 after Boss Blinds', '🚀'),
  joker('rough-gem', 'Rough Gem', 'uncommon', 7, 'Scored Diamonds earn $1', '♦'),
  joker('satellite', 'Satellite', 'uncommon', 6, 'Earn $1 per unique hand type played after each Blind', '🛰'),
  joker('seance', 'Séance', 'uncommon', 6, 'Straight Flushes earn $6', '☾'),
  joker('seeing-double', 'Seeing Double', 'uncommon', 6, 'X2 Mult when a Club and another suit score', '◉'),
  joker('seltzer', 'Seltzer', 'uncommon', 6, 'All scoring cards retrigger for ten hands', '🥤'),
  joker('shortcut', 'Shortcut', 'uncommon', 7, 'Straights may contain one-rank gaps', '↗'),
  joker('showman', 'Showman', 'uncommon', 5, 'Duplicate Jokers can appear in the shop', '🎭'),
  joker('sixth-sense', 'Sixth Sense', 'uncommon', 6, 'A single 6 as the first hand earns $6', '6'),
  joker('smeared', 'Smeared Joker', 'uncommon', 7, 'Red suits and black suits count together for Flushes', '◐'),
  joker('sock-and-buskin', 'Sock and Buskin', 'uncommon', 6, 'Scored face cards retrigger', '🎭'),
  joker('space-joker', 'Space Joker', 'uncommon', 5, 'Hands can gain a permanent level', '★'),
  joker('spare-trousers', 'Spare Trousers', 'uncommon', 6, 'Two Pair permanently adds +2 Mult', 'Ⅱ'),
  joker('steel-joker', 'Steel Joker', 'uncommon', 7, 'Gains X0.2 Mult every five hands', '⚙'),
  joker('stone-joker', 'Stone Joker', 'uncommon', 6, '+25 Chips per cleared Boss Blind', '●'),
  joker('the-idol', 'The Idol', 'uncommon', 6, 'Scored 7s give X2 Mult', '7'),
  joker('throwback', 'Throwback', 'uncommon', 6, 'X0.25 Mult per skipped Blind', '↶'),
  joker('to-the-moon', 'To the Moon', 'uncommon', 5, 'Earn additional interest after every Blind', '☾'),
  joker('trading-card', 'Trading Card', 'uncommon', 6, 'First single-card discard earns $3', '↔'),
  joker('troubadour', 'Troubadour', 'uncommon', 6, '+2 hand size and -1 hand each Blind', '♫'),
  joker('turtle-bean', 'Turtle Bean', 'uncommon', 6, '+5 hand size, loses one after each Blind', '◒'),
  joker('vampire', 'Vampire', 'uncommon', 7, 'Gains X0.1 Mult for every five scoring cards', 'V'),
  joker('ancient-joker', 'Ancient Joker', 'rare', 8, 'One random suit gives X1.5 Mult when scored', 'A'),
  joker('baron', 'Baron', 'rare', 8, 'Held Kings give X1.5 Mult each', 'K'),
  joker('baseball-card', 'Baseball Card', 'rare', 8, 'Each owned Uncommon Joker gives X1.5 Mult', '⚾'),
  joker('blueprint', 'Blueprint', 'rare', 10, 'Copies the strongest Joker bonus', 'B'),
  joker('brainstorm', 'Brainstorm', 'rare', 10, 'Copies the leftmost scoring Joker', '🧠'),
  joker('burnt-joker', 'Burnt Joker', 'rare', 8, 'First discard each Blind upgrades future hands', '🔥'),
  joker('campfire', 'Campfire', 'rare', 9, 'Gains X0.25 Mult whenever a Joker is sold', '🔥'),
  joker('dna', 'DNA', 'rare', 8, 'Single-card first hands gain +50 Chips', 'DNA'),
  joker('drivers-license', "Driver's License", 'rare', 7, 'X3 Mult after playing at least 16 hands', 'ID'),
  joker('hit-the-road', 'Hit the Road', 'rare', 8, 'Discarded Jacks add X0.5 Mult this Blind', 'J'),
  joker('invisible-joker', 'Invisible Joker', 'rare', 8, 'After two Blinds, sells for $16', '◌'),
  joker('obelisk', 'Obelisk', 'rare', 8, 'Gains X0.2 Mult while varying hand types', '▴'),
  joker('stuntman', 'Stuntman', 'rare', 7, '+250 Chips and -2 hand size', 'S'),
  joker('the-duo', 'The Duo', 'rare', 8, 'X2 Mult on hands containing a Pair', '2'),
  joker('the-family', 'The Family', 'rare', 8, 'X4 Mult on Four of a Kind', '4'),
  joker('the-order', 'The Order', 'rare', 8, 'X3 Mult on a Straight', '5'),
  joker('the-tribe', 'The Tribe', 'rare', 8, 'X2 Mult on a Flush', '♠'),
  joker('the-trio', 'The Trio', 'rare', 8, 'X3 Mult on Three of a Kind', '3'),
  joker('vagabond', 'Vagabond', 'rare', 8, 'Hands played at $4 or less earn $3', 'V'),
  joker('wee-joker', 'Wee Joker', 'rare', 8, 'Scored 2s permanently add +8 Chips', '2'),
  joker('canio', 'Canio', 'legendary', 20, 'Face-card discards permanently add X0.2 Mult', 'C'),
  joker('chicot', 'Chicot', 'legendary', 20, 'Disables Boss Blind penalties', 'C'),
  joker('perkeo', 'Perkeo', 'legendary', 20, 'Leaving the shop grants $5', 'P'),
  joker('triboulet', 'Triboulet', 'legendary', 20, 'Scored Kings and Queens give X2 Mult', 'KQ'),
  joker('yorick', 'Yorick', 'legendary', 20, 'Every 23 discarded cards permanently adds X1 Mult', 'Y')
];

export const BALATRO_JOKERS: JokerDefinition[] = JOKER_DEFINITIONS.map((entry, artIndex) => ({
  ...entry,
  artIndex
}));

export const jokerById = (id: string): JokerDefinition | undefined =>
  BALATRO_JOKERS.find((entry) => entry.id === id);
